version: '3.3'

volumes:
  blog_postgres_volume:

secrets:
  jwt-secret:
    file: jwt-secret.txt

services:
  blog_back:
    build:
      context: .
      dockerfile: DockerfileBack
    container_name: blog_back
    ports:
      - '7007:7000'
    depends_on:
      - blog_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://blog_db:5432/postgres
      FRONT_URL: front
      JWT_SECRET: jwt-secret
    secrets:
      - jwt-secret

  blog_front:
    build:
      context: .
      dockerfile: DockerfileFront
    container_name: blog_front
    ports:
      - '80:80'

  blog_db:
    image: postgres:latest
    container_name: blog_db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - blog_postgres_volume:/var/lib/postgresql/data