version: '3.3'

volumes:
  reactive_tales_blog_postgres_volume:

services:
  reactive_tales_blog_postgres:
    image: postgres:latest
    container_name: reactive_tales_blog_postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - reactive_tales_blog_postgres_volume:/var/lib/postgresql/data
