server:
  port: 8080
  servlet:
    contextPath: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/blog
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
